name: flutter_geofencing
description: A geofencing plugin for Flutter applications - Works on both Android and iOS - supports Android X - based on Ben Konyi's Geofencing.
version: 0.1.1
author: Karim Abdo & BÃ¼lent Hacioglu based on Ben Konyi <karim.abdo@petleo.net>
homepage: https://github.com/KarimAbdo/FlutterGeofencing

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.flutter.plugins.geofencing
    pluginClass: GeofencingPlugin